#!/usr/bin/env bash
#
# Generate the cloudflared config for a ChengOS origin.
#
# With a tunnel the origin publishes nothing: cloudflared dials out to
# Cloudflare and requests come back down that connection. There is no inbound
# port on the public internet, so there is no port to scan, no origin firewall
# to maintain, and no origin certificate to obtain or renew. It also removes
# the need for a separate proxy VPS — the Cloudflare edge is the proxy.
#
# This script writes config files only. Creating the tunnel needs an
# interactive browser login and issues credentials, so those steps are printed
# for you to run rather than automated here.
#
#   ./setup-tunnel.sh --ui chengos.example.com --app app.example.com
#   ./setup-tunnel.sh --ui chengos.example.com --out /tmp/preview
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
ENV_FILE="${REPO_ROOT}/deploy/.env"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

UI_HOST=""
APP_HOST=""
OUT_DIR="${HERE}/tunnel/generated"
TUNNEL_NAME="chengos"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ui)     UI_HOST="$2"; shift 2 ;;
    --app)    APP_HOST="$2"; shift 2 ;;
    --name)   TUNNEL_NAME="$2"; shift 2 ;;
    --out)    OUT_DIR="$2"; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

[[ -n "$UI_HOST" ]] || { echo "--ui <hostname> is required" >&2; exit 2; }

read_env() {
  local key="$1" fallback="$2"
  local value=""
  [[ -f "$ENV_FILE" ]] && value="$(sed -n "s/^${key}=\(.*\)$/\1/p" "$ENV_FILE" | tail -n1 | tr -d '[:space:]')"
  printf '%s' "${value:-$fallback}"
}

UI_PORT="$(read_env UI_PORT 8080)"
APP_PORT="$(read_env APP_PORT 5055)"

# Universal SSL covers the apex and ONE level of subdomain. A two-level name
# like app.ai.example.com gets no certificate on the free plan and fails in the
# browser with a TLS error that looks nothing like a naming problem.
warn_depth() {
  local host="$1" label="$2"
  # Three dots means four labels, i.e. two levels below a two-label apex.
  # chengos.example.com (two dots) is exactly one level down and is covered.
  local dots
  dots="$(tr -cd '.' <<<"$host" | wc -c)"
  (( dots >= 3 )) || return 0

  # Suggest <first label>.<apex>, where the apex is taken as the last two
  # labels. That is right for example.com and wrong for a multi-part public suffix
  # such as example.co.uk, so it is phrased as a suggestion rather than a rule.
  local first apex
  first="${host%%.*}"
  apex="$(awk -F. '{ print $(NF-1)"."$NF }' <<<"$host")"

  cat >&2 <<EOF

WARNING: ${label} hostname "${host}" is more than one level below the apex.

  Cloudflare's free Universal SSL certificate covers example.com and
  *.example.com — ONE level of subdomain. A deeper name gets no certificate
  unless you buy Advanced Certificate Manager, and the browser reports a TLS
  error that looks nothing like a naming problem.

  Suggested instead: ${first}.${apex}
  (assumes a two-label apex; adjust for a suffix like example.co.uk)

EOF
}

warn_depth "$UI_HOST" "UI"
[[ -n "$APP_HOST" ]] && warn_depth "$APP_HOST" "App"

mkdir -p "$OUT_DIR"
CONFIG="${OUT_DIR}/config.yml"

{
  cat <<EOF
# cloudflared config for ChengOS — GENERATED by deploy/infra/cloudflare/setup-tunnel.sh
#
# Install to /etc/cloudflared/config.yml and replace TUNNEL_UUID below with the
# id printed by \`cloudflared tunnel create ${TUNNEL_NAME}\`.

tunnel: TUNNEL_UUID
credentials-file: /etc/cloudflared/TUNNEL_UUID.json

# QUIC is the default and worth keeping: it rides out packet loss on a
# long-haul link far better than http2. Switch to http2 only if your provider
# blocks outbound UDP to port 7844.
protocol: quic

# Prometheus metrics and the readiness endpoint, on loopback only. Nothing
# about this is reachable from outside the box.
metrics: 127.0.0.1:2000

loglevel: info

ingress:
  # The UI server already proxies /api and /ws to the backend, so the tunnel
  # points at it alone. The API is NOT published: exposing it here would put it
  # beside the hardened frontend instead of behind it, and every scanner rule
  # and rate limit would be bypassable by calling it directly.
  - hostname: ${UI_HOST}
    service: http://127.0.0.1:${UI_PORT}
    originRequest:
      connectTimeout: 10s
      # No TLS on this hop and none needed: it is a loopback connection that
      # never touches a network interface. The encrypted leg is cloudflared's
      # own outbound connection to Cloudflare.
      httpHostHeader: ${UI_HOST}
EOF

  if [[ -n "$APP_HOST" ]]; then
    cat <<EOF

  - hostname: ${APP_HOST}
    service: http://127.0.0.1:${APP_PORT}
    originRequest:
      connectTimeout: 10s
      httpHostHeader: ${APP_HOST}
EOF
  fi

  cat <<'EOF'

  # A catch-all must come last or cloudflared refuses to start. 404, not a
  # service: a request that matched no hostname above is not for this origin.
  - service: http_status:404
EOF
} > "$CONFIG"

cp "${HERE}/tunnel/cloudflared.service" "${OUT_DIR}/cloudflared.service"

if command -v python3 >/dev/null; then
  python3 -c "import sys,yaml; yaml.safe_load(open(sys.argv[1]))" "$CONFIG" \
    && echo "config.yml parses as valid YAML"
fi

cat <<EOF

Wrote:
  ${CONFIG}
  ${OUT_DIR}/cloudflared.service

Next, on the origin host. These need an interactive browser login and they
mint credentials, so run them yourself rather than from a script:

  1. Install cloudflared, then authenticate (opens a browser):
       cloudflared tunnel login

  2. Create the tunnel and note the UUID it prints:
       cloudflared tunnel create ${TUNNEL_NAME}

  3. Point the hostnames at it. This writes proxied CNAME records for you —
     no DNS records to create by hand, and they are orange-clouded by
     definition:
       cloudflared tunnel route dns ${TUNNEL_NAME} ${UI_HOST}$( [[ -n "$APP_HOST" ]] && printf '\n       cloudflared tunnel route dns %s %s' "$TUNNEL_NAME" "$APP_HOST" )

  4. Install the config, substituting the UUID from step 2:
       sudo mkdir -p /etc/cloudflared
       sudo cp ${CONFIG} /etc/cloudflared/config.yml
       sudo sed -i "s/TUNNEL_UUID/<uuid-from-step-2>/g" /etc/cloudflared/config.yml
       sudo cp ~/.cloudflared/<uuid>.json /etc/cloudflared/

  5. Create the service account and lock down the credentials. The json file
     is a bearer credential for this tunnel — anyone who reads it can serve
     traffic on your hostnames:
       sudo useradd --system --no-create-home --shell /usr/sbin/nologin cloudflared
       sudo chown -R root:cloudflared /etc/cloudflared
       sudo chmod 750 /etc/cloudflared
       sudo chmod 640 /etc/cloudflared/*.json /etc/cloudflared/config.yml

  6. Start it:
       sudo cp ${OUT_DIR}/cloudflared.service /etc/systemd/system/
       sudo systemctl daemon-reload
       sudo systemctl enable --now cloudflared
       systemctl status cloudflared

Then set these in ${ENV_FILE} and restart ChengOS:

  BIND_ADDRESS=127.0.0.1
  UI_BIND=127.0.0.1
  APP_BIND=127.0.0.1
  TRUST_CLOUDFLARE=true

TRUST_CLOUDFLARE matters here. cloudflared reaches the frontends over loopback,
which is trusted implicitly, and it forwards CF-Connecting-IP — without the
flag the real visitor address is still recovered from X-Forwarded-For, but with
it the value comes from the header Cloudflare writes itself.

Finally, close the inbound ports. Once the tunnel is healthy nothing should
reach this host from the internet at all:

  sudo ufw deny 80/tcp && sudo ufw deny 443/tcp

Do NOT run origin-firewall.sh in this deployment. It allowlists Cloudflare's
ranges for inbound 80/443, which is the wrong shape here: with a tunnel there
is no inbound connection to allow.
EOF
